language: r
sudo: false
cache: packages

matrix:
  include:
  - r: release
    r_github_packages: r-lib/covr
    after_success: Rscript -e 'covr::codecov()'
  - r: devel
  - r: oldrel


notifications:
  email:
    on_success: change
    on_failure: change